name: Update Subscribers and Followers

on:
  schedule:
    - cron: '0 11 * * *' # Runs at 11 AM UTC (12 PM BST)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc

      - name: Run Twitter Followers Script
        run: node twitterFollowers.js

      - name: Run YouTube Subscribers Script
        run: node ytSubs.js
